/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cabinet_veterinar_app;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alexa
 */
public class StatisticiForm extends javax.swing.JFrame {

    /**
     * Creates new form StatisticiForm
     */
    public StatisticiForm() {
        initComponents();
        fillCombo();
        fillCombo2();
        fillCombo3();
        fillCombo4();
        fillCombo5();
    }
    
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    
    public Connection getConnection()
    {
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Cabinet_veterinar;user=alexandra;password=12345");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(FormularCabinet.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_doctori = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox_tip = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_arata3 = new javax.swing.JButton();
        jComboBox_tip1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_doctori1 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_proceduri = new javax.swing.JComboBox();
        jTextField6 = new javax.swing.JTextField();
        show = new javax.swing.JButton();
        jComboBox_stapani = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_procedura = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton_show1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton_show2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton_arata2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox_status = new javax.swing.JComboBox();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox_prioritate = new javax.swing.JComboBox();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back1.jpg"))); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(0, 0, 125, 61);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Statistici Cabinet");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(589, 22, 195, 29);

        jComboBox_doctori.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jComboBox_doctori);
        jComboBox_doctori.setBounds(707, 423, 138, 22);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_complex2.png"))); // NOI18N
        jButton5.setText("Arata");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(800, 160, 125, 59);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("De cate animale de tipul");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(203, 422, 155, 24);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jTextField9);
        jTextField9.setBounds(1457, 172, 69, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("s-a ocupat doctorul");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(523, 426, 128, 16);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_simple2.jpg"))); // NOI18N
        jButton2.setText("Arata");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(49, 405, 140, 59);

        jComboBox_tip.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboBox_tip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_tip);
        jComboBox_tip.setBounds(390, 423, 81, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Suma platita:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(726, 564, 86, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Castigul total al clinicii");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(189, 319, 142, 16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Exista in baza de date a cabinetului");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1211, 175, 228, 16);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(359, 316, 235, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("au fost facute");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 250, 120, 16);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Cati doctori au avut vizite cu prioritate");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(960, 320, 260, 16);

        jButton_arata3.setBackground(new java.awt.Color(255, 255, 255));
        jButton_arata3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_arata3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_complex2.png"))); // NOI18N
        jButton_arata3.setText("Arata");
        jButton_arata3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_arata3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_arata3);
        jButton_arata3.setBounds(50, 300, 130, 59);

        jComboBox_tip1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jComboBox_tip1);
        jComboBox_tip1.setBounds(1113, 172, 80, 22);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_simple2.jpg"))); // NOI18N
        jButton3.setText("Arata");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(49, 471, 140, 59);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(908, 423, 69, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Propietarul care i-a facut cele mai multe vizite doctorului ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 500, 372, 16);

        jComboBox_doctori1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jComboBox_doctori1);
        jComboBox_doctori1.setBounds(630, 500, 136, 22);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(820, 500, 114, 22);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_simple2.jpg"))); // NOI18N
        jButton4.setText("Arata");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(49, 638, 140, 59);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Propietarul care si-a dus de cele mai multe ori animalele la cabinet pentru ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(203, 659, 480, 16);

        jComboBox_proceduri.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jComboBox_proceduri);
        jComboBox_proceduri.setBounds(701, 656, 161, 22);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(898, 656, 220, 22);

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_simple2.jpg"))); // NOI18N
        show.setText("Arata");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show);
        show.setBounds(49, 543, 140, 59);

        jComboBox_stapani.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jComboBox_stapani);
        jComboBox_stapani.setBounds(392, 172, 180, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Cate proceduri de tip");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(189, 247, 137, 16);

        jComboBox_procedura.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jComboBox_procedura);
        jComboBox_procedura.setBounds(350, 240, 180, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Numele animalului pentru care s-a platit cel mai mult");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(207, 564, 337, 16);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Cate animale are propietarul");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(189, 175, 185, 16);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(590, 172, 56, 22);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(847, 561, 83, 22);

        jButton_show1.setBackground(new java.awt.Color(255, 255, 255));
        jButton_show1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_complex2.png"))); // NOI18N
        jButton_show1.setText("Arata");
        jButton_show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_show1);
        jButton_show1.setBounds(47, 154, 130, 59);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(577, 561, 131, 30);

        jButton_show2.setBackground(new java.awt.Color(255, 255, 255));
        jButton_show2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_complex2.png"))); // NOI18N
        jButton_show2.setText("Arata");
        jButton_show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_show2);
        jButton_show2.setBounds(47, 226, 130, 59);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(680, 250, 56, 22);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\OneDrive\\Documents\\NetBeansProjects\\test\\src\\images\\zampe-sugli-animali-domestici-messi-90987408.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(800, 400, 1140, 380);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexa\\OneDrive\\Documents\\NetBeansProjects\\test\\src\\images\\dogsheads.jpg")); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(480, 10, 600, 160);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_complex2.png"))); // NOI18N
        jButton7.setText("Arata");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(800, 300, 130, 59);

        jButton_arata2.setBackground(new java.awt.Color(255, 255, 255));
        jButton_arata2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_arata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye_complex2.png"))); // NOI18N
        jButton_arata2.setText("Arata");
        jButton_arata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_arata2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_arata2);
        jButton_arata2.setBounds(800, 230, 130, 59);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Cate animale de tip");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(963, 175, 124, 16);

        jComboBox_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Programata", "Realizata" }));
        jPanel1.add(jComboBox_status);
        jComboBox_status.setBounds(1130, 250, 100, 22);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(1270, 250, 130, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Cate animale au statusul");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(960, 250, 170, 16);

        jComboBox_prioritate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Scazuta", "Medie", "Ridicata" }));
        jPanel1.add(jComboBox_prioritate);
        jComboBox_prioritate.setBounds(1230, 320, 90, 22);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(1350, 320, 120, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1555, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show1ActionPerformed
        try{  
            String sql = "select count(A.Nume) "
                  + "from Animal A RIGHT JOIN Propietar P "
                  + "ON A.IdStapan = P.IdPropietar "
                  + "where P.Nume=? AND P.Prenume=?";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            String combo = (String)jComboBox_stapani.getSelectedItem();
            String[] splited = combo.split(" ");
            ps.setString(1, splited[0]);
            ps.setString(2, splited[1]);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("");
                jTextField1.setText(temp);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_show1ActionPerformed

    private void jButton_show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show2ActionPerformed
        try{  
            String sql = "select count(IdVizita) "
                  + "from Procedura P LEFT JOIN VizitaProcedura V "
                  + "ON P.IdProcedura = V.IdProcedura "
                  + "where P.Denumire=?";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            String combo = (String)jComboBox_procedura.getSelectedItem();
            ps.setString(1, combo);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("");
                jTextField2.setText(temp);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_show2ActionPerformed

    private void jButton_arata3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_arata3ActionPerformed
       try{  
            String sql = "select sum(cost) "
                  + "from Procedura P INNER JOIN VizitaProcedura V "
                  + "ON P.IdProcedura = V.IdProcedura ";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            //String combo = (String)jComboBox_procedura.getSelectedItem();
            //ps.setString(1, combo);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("");
                jTextField3.setText(temp);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_arata3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{  
            String sql = "SELECT COUNT (distinct SEL_ANM.Nume) " +
                        "FROM " +
                        "(SELECT A.IdAnimal, A.Nume, A.IdRasa " +
                        "FROM Animal A RIGHT JOIN " +
                        "(SELECT T.Denumire, R.IdRasa " +
                        "FROM TipAnimal T LEFT JOIN Rasa R " +
                        "ON T.IdTip = R.IdTip " +
                        "WHERE T.Denumire = ?) as SEL_TIP " +
                        "on A.IdRasa = SEL_TIP.IdRasa) as SEL_ANM INNER JOIN " +
                        "(SELECT Ang.IdAngajat, Ang.Nume, V.IdPacient " +
                        "FROM Angajat Ang LEFT JOIN Vizita V " +
                        "on Ang.IdAngajat = V.IdDoctor " +
                        "WHERE Ang.Nume = ? AND Ang.Prenume = ?) as SEL_ANG " +
                        "on SEL_ANM.IdAnimal = SEL_ANG.IdPacient";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            String comb = (String)jComboBox_tip.getSelectedItem();
            String combo = (String)jComboBox_doctori.getSelectedItem();
            String[] splited = combo.split(" ");
            ps.setString(1, comb);
            ps.setString(2, splited[0]);
            ps.setString(3, splited[1]);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("");
                jTextField4.setText(temp);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{  
            String sql ="SELECT TOP 1 COUNT(y.Nume) as cont, y.Nume, y.Prenume " +
                        "FROM " +
                        "(SELECT SEL_PROP.Nume, SEL_PROP.Prenume " +
                        "FROM (SELECT P.Nume, P.Prenume, A.IdAnimal " +
                        "FROM Propietar P INNER JOIN Animal A " +
                        "ON P.IdPropietar = A.IdStapan) AS SEL_PROP " +
                        "INNER JOIN " +
                        "(SELECT V.IdPacient " +
                        "FROM Angajat Ang INNER JOIN Vizita V " +
                        "on Ang.IdAngajat = V.IdDoctor " +
                        "WHERE Ang.Nume = ? AND Ang.Prenume = ?) as SEL_DOC " +
                        "on SEL_PROP.IdAnimal = SEL_DOC.IdPacient) as y " +
                        "GROUP BY y.Nume, y.Prenume " +
                        "ORDER BY cont DESC ";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            String combo = (String)jComboBox_doctori1.getSelectedItem();
            String[] splited = combo.split(" ");
            ps.setString(1, splited[0]);
            ps.setString(2, splited[1]);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("Nume");
                String temp2 = rs.getString("Prenume");
                jTextField5.setText(temp + " " + temp2);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{  
            jTextField6.setText("Nu a fost realizata procedura ");
            String sql ="SELECT TOP 1 count(SEL_PROC.IdVizita) as cont, SEL_VIZ.Nume, SEL_VIZ.Prenume " +
                        "FROM " +
                        "(SELECT SEL_PROP_AN.Nume, SEL_PROP_AN.Prenume, V.IdVizita " +
                        "FROM " +
                        "(SELECT P.Nume, P.Prenume, A.IdAnimal " +
                        "FROM Propietar P INNER JOIN Animal A " +
                        "on P.IdPropietar = A.IdStapan) as SEL_PROP_AN " +
                        "INNER JOIN Vizita V " +
                        "on V.IdPacient = SEL_PROP_AN.IdAnimal) as SEL_VIZ " +
                        "INNER JOIN " +
                        "(SELECT VP.IdVizita " +
                        "FROM Procedura Pr LEFT JOIN VizitaProcedura VP " +
                        "on Pr.IdProcedura = VP.IdProcedura " +
                        "where Pr.Denumire = ?) as SEL_PROC " +
                        "on SEL_VIZ.IdVizita = SEL_PROC.IdVizita " +
                        "group by SEL_VIZ.Nume, SEL_VIZ.Prenume " +
                        "order by cont DESC";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            String combo = (String)jComboBox_proceduri.getSelectedItem();
            ps.setString(1, combo);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("Nume");
                String temp2 = rs.getString("Prenume");                   
                jTextField6.setText(temp + " " + temp2);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        try{  
            String sql ="SELECT TOP 1 SUM(SEL_P.Cost) as total, SEL_AN.Nume " +
                        "FROM (SELECT A.Nume, A.IdAnimal, V.IdVizita " +
                        "FROM Animal A INNER JOIN Vizita V " +
                        "on A.IdAnimal = V.IdPacient) as SEL_AN " +
                        "INNER JOIN " +
                        "(SELECT P.Cost, P.IdProcedura, VP.IdVizita " +
                        "FROM Procedura P INNER JOIN VizitaProcedura VP " +
                        "on P.IdProcedura = VP.IdProcedura) as SEL_P " +
                        "on SEL_AN.IdVizita = SEL_P.IdVizita " +
                        "group by SEL_AN.Nume " +
                        "order by total DESC ";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("Nume");
                String temp2 = rs.getString("total");
                jTextField7.setText(temp);
                jTextField8.setText(temp2);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_showActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{  
            String sql ="select count(A.IdAnimal) as Numar " +
                        "from Animal A RIGHT JOIN Rasa R " +
                        "on A.IdRasa = R.IdRasa " +
                        "RIGHT JOIN TipAnimal T " +
                        "on T.IdTip = R.IdTip " +
                        "where T.Denumire = ? ";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            String combo = (String)jComboBox_tip1.getSelectedItem();
            ps.setString(1, combo);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("Numar");
                jTextField9.setText(temp);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        close();
        Meniu f = new Meniu();
        f.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox_tipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tipActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{  
            String sql ="Select count(distinct A.IdAngajat) as contor " +
                        "from Angajat A INNER JOIN Vizita V " +
                        "on A.IdAngajat = V.IdDoctor " +
                        "where V.Prioritate = ? ";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            String combo = (String)jComboBox_prioritate.getSelectedItem();
            ps.setString(1, combo);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("contor");
                jTextField11.setText(temp);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton_arata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_arata2ActionPerformed
        try{  
            String sql ="Select count(distinct A.IdAnimal) as contor " +
                        "from Animal A INNER JOIN Vizita V " +
                        "on A.IdAnimal = V.IdPacient " +
                        "where V.Status = ? ";
            Connection conn=getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            String combo = (String)jComboBox_status.getSelectedItem();
            ps.setString(1, combo);
            ResultSet rs = ps.executeQuery();
               
            while(rs.next()){
                String temp = rs.getString("contor");
                jTextField10.setText(temp);
                  }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_arata2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticiForm().setVisible(true);
            }
        });
    }
    
    
    private void fillCombo(){
        try{
          String sql = "select * from Propietar ";
          Connection conn=getConnection();
          PreparedStatement ps = conn.prepareStatement(sql);
          ResultSet rs = ps.executeQuery();
          
          while(rs.next()){
              String nume = rs.getString("Nume");
              String prenume = rs.getString("Prenume");
              jComboBox_stapani.addItem(nume + " " + prenume);
          }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void fillCombo2(){
        try{
          String sql = "select * from Procedura ";
          Connection conn=getConnection();
          PreparedStatement ps = conn.prepareStatement(sql);
          ResultSet rs = ps.executeQuery();
          
          while(rs.next()){
              String nume = rs.getString("Denumire");
              jComboBox_procedura.addItem(nume);
          }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
     private void fillCombo3(){
        try{
          String sql = "select * from TipAnimal ";
          Connection conn=getConnection();
          PreparedStatement ps = conn.prepareStatement(sql);
          ResultSet rs = ps.executeQuery();
          
          while(rs.next()){
              String nume = rs.getString("Denumire");
              jComboBox_tip.addItem(nume);
              jComboBox_tip1.addItem(nume);
          }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     
     private void fillCombo4(){
        try{
          String sql = "select * from Angajat ";
          Connection conn=getConnection();
          PreparedStatement ps = conn.prepareStatement(sql);
          ResultSet rs = ps.executeQuery();
          
          while(rs.next()){
              String nume = rs.getString("Nume");
              String prenume = rs.getString("Prenume");
              jComboBox_doctori.addItem(nume + " " + prenume);
              jComboBox_doctori1.addItem(nume + " " + prenume);
          }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     
     private void fillCombo5(){
        try{
          String sql = "select * from Procedura ";
          Connection conn=getConnection();
          PreparedStatement ps = conn.prepareStatement(sql);
          ResultSet rs = ps.executeQuery();
          
          while(rs.next()){
              String nume = rs.getString("Denumire");
              jComboBox_proceduri.addItem(nume);
          }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_arata2;
    private javax.swing.JButton jButton_arata3;
    private javax.swing.JButton jButton_show1;
    private javax.swing.JButton jButton_show2;
    private javax.swing.JComboBox jComboBox_doctori;
    private javax.swing.JComboBox jComboBox_doctori1;
    private javax.swing.JComboBox jComboBox_prioritate;
    private javax.swing.JComboBox jComboBox_procedura;
    private javax.swing.JComboBox jComboBox_proceduri;
    private javax.swing.JComboBox jComboBox_stapani;
    private javax.swing.JComboBox jComboBox_status;
    private javax.swing.JComboBox jComboBox_tip;
    private javax.swing.JComboBox jComboBox_tip1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
